import type { ExperienceItem } from "@/types/experience"

export const experiences: ExperienceItem[] = [
  {
    id: "independent-software-engineer",
    role: "Independent Software Engineer",
    company: "Self-Employed",
    period: "May 2025 - Present",
    location: "Dhaka, Bangladesh",
    current: true,
    contractType: "independent",
    workMode: "remote",
    impact: [
      "Built and maintain backendctl, an open source backend project starter — github.com/dipto0321/backendctl",
      "Building a full-stack personal finance tracking application (FastAPI, PostgreSQL, React), with open source release planned",
      "Developing a note-taking application using FastAPI to deepen backend architecture, authentication, and API design skills",
      "Built a job-aggregation and automation toolkit to streamline sourcing of opportunities across multiple platforms",
      "Strengthened full-stack capabilities through applied learning in Django, FastAPI, Next.js, and GSAP",
      "Following a structured AI engineering roadmap covering LLMs, agentic systems, and applied AI tooling",
    ],
    technologies: ["FastAPI", "Python", "PostgreSQL", "Next.js", "React", "Django", "Node.js"],
  },
  {
    id: "myze-senior-frontend-engineer",
    role: "Senior Frontend Engineer",
    company: "Myze",
    period: "Mar 2025 - Apr 2025",
    location: "Emmerich, Germany",
    contractType: "contract",
    workMode: "remote",
    impact: [
      "Led development of a real-time tablet checkout interface in React and TypeScript with multilingual support and integrated SumUp payments.",
      "Engineered WebSocket-based systems for device pairing and live payment tracking, improving transparency and reducing customer wait times.",
      "Built reusable, scalable UI components — tabbed product views, color picker inputs, and GraphQL-powered data tables.",
      "Collaborated with backend engineers to define API contracts, ensuring reliable real-time state synchronization in production.",
    ],
    technologies: ["React", "TypeScript", "GraphQL", "WebSockets", "SumUp"],
  },
  {
    id: "proptechcore-senior-frontend-engineer",
    role: "Senior Frontend Engineer",
    company: "ProptechCore",
    period: "Oct 2022 - Feb 2025",
    location: "Stockholm, Sweden",
    contractType: "full-time",
    workMode: "remote",
    impact: [
      "Spearheaded transformation of Figma design systems into production-grade React component libraries, streamlining UI development across teams.",
      "Delivered pixel-perfect, accessible B2B SaaS interfaces across complex user flows with full design fidelity and performance.",
      "Designed and maintained a centralized component library enabling consistent UI and faster iteration across teams.",
      "Owned end-to-end user onboarding and invitation flows, from design through delivery.",
      "Built real-time office energy monitoring dashboards with WebSocket data pipelines, balancing UX clarity with data accuracy.",
      "Provided frontend architecture decisions, estimations, and cross-team technical feedback autonomously in a remote-first environment.",
    ],
    technologies: ["React", "TypeScript", "Next.js", "WebSockets", "Design Systems", "GraphQL"],
  },
  {
    id: "kiwibot-senior-frontend-engineer",
    role: "Senior Frontend Engineer",
    company: "Kiwibot",
    period: "Aug 2021 - May 2022",
    location: "Medellín, Colombia",
    contractType: "full-time",
    workMode: "remote",
    impact: [
      "Led refactor of a legacy console application into a scalable micro-frontend architecture using Nx, improving maintainability and enabling team growth.",
      "Applied a complete brand and UI theme across the application without dedicated design support, ensuring visual consistency.",
      "Implemented a real-time task notification system using WebSockets, improving supervisor visibility and response time.",
    ],
    technologies: ["React", "TypeScript", "Nx", "WebSockets", "Micro-frontends"],
  },
  {
    id: "youmewho-full-stack-developer",
    role: "Full Stack Developer",
    company: "YouMeWho",
    period: "Feb 2021 - May 2021",
    location: "Palo Alto, California, USA",
    contractType: "contract",
    workMode: "remote",
    impact: [
      "Built a Chrome extension to auto-scrape and import merchandise, improving client inventory management speed.",
      "Researched and proposed Facebook API integrations for real-time social media marketing features.",
    ],
    technologies: ["JavaScript", "Chrome Extensions", "REST APIs", "Facebook API"],
  },
  {
    id: "chosenmasters-full-stack-developer",
    role: "Full Stack Developer",
    company: "Chosenmasters",
    period: "Sep 2020 - Dec 2020",
    location: "Vancouver, Canada",
    contractType: "contract",
    workMode: "remote",
    impact: [
      "Developed a music streaming platform supporting track uploads, merchandise sales, and social features (favorites, follows).",
      "Delivered e-commerce and audio streaming functionality enabling artist monetization and user growth.",
    ],
    technologies: ["React", "Node.js", "PostgreSQL", "REST APIs"],
  },
  {
    id: "anansi-skills-back-end-developer",
    role: "Back End Developer",
    company: "Anansi Skills",
    period: "Dec 2019 - Jan 2020",
    location: "Chapel Hill, NC, USA",
    contractType: "contract",
    workMode: "remote",
    impact: [
      "Designed a social-auth enabled, role-based REST API with full Swagger documentation.",
      "Deployed a Keras-based deep learning model on GCP for educational analytics.",
    ],
    technologies: ["Python", "Django", "REST APIs", "GCP", "Keras"],
  },
  {
    id: "microverse-technical-support-engineer",
    role: "Technical Support Engineer",
    company: "Microverse",
    period: "Jun 2019 - Aug 2019",
    location: "San Francisco Bay Area, USA",
    contractType: "full-time",
    workMode: "remote",
    impact: [
      "Led 400+ code reviews in Ruby, Rails, JavaScript, and React for 50+ students, accelerating learning through tailored 1:1 guidance.",
      "Mentored 20+ students to graduation, improving retention and technical confidence.",
      "Managed 10+ part-time code reviewers, maintaining high standards and consistency across the review process.",
    ],
    technologies: ["Ruby", "Rails", "React", "JavaScript"],
  },
]
